### ISSUE TITLE
No alumni option

### ISSUE THREAD

**Issue by maxbulger** [ilangray/solvecs#9]
Semantic issue, not a bug. Would be great to have an alumni option in class drop-down.

**Comment by samueldaniel** [comment]
Yes, we are aware of this issue. Right now we have the site validating on "tufts.edu" email addresses in the interest of focusing this on the Tufts community - obviously, as an alum, you are a part of that community. tbh we built it in a 6 hour sprint and haven't had the time since then to update it. We will work on it! Thanks for the input!
